blank_issues_enabled: false
contact_links:
  - name: Ask a question
    about: Ask questions and discuss with other users of the library.
    url: https://github.com/Pycord-Development/pycord/discussions
  - name: Fosscord Server
    about: Use our official Fosscord server to ask for help and questions as well.
    url: https://fosscord.gg/UCXwPR7Pew
